SnippetsDev/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('snippets.urls')),

]

snippets/urls.py
from django.urls import path

from snippets import views

app_name = 'snippets'

urlpatterns = [
    path('', views.homeView, name= 'Home'),
    path('addSnippet/', views.addSnippetView, name= 'AddSnip'),
    path('editSnippet/<int:pk>/', views.editSnippetView.as_view(), name= 'EditSnip'),
    path('deleteSnippet/<int:pk>/', views.deleteSnippetView.as_view(), name= 'DelSnip'),
    path('addLanguage/', views.addLanguageView, name= 'AddLang'),
    path('addPackage/', views.addPackageView, name= 'AddPack'),
    path('addApplication/', views.addApplicationView, name= 'AddApp'),
    # These are JSON return used by JS to get lists of objects
    path('getlanguages/', views.getLanguages, name= 'GetLangs'),
    path('getpackages/', views.getPackages, name= 'GetPacks'),
    path('getapplications/', views.getApplications, name= 'GetApps'),
    # Load the filtered snippets
    path('languages/<str:lang>/', views.filterByLanguageView, name= 'LangView'),
    path('packages/<str:pack>/', views.filterByPackageView, name= 'PackView'),
    path('applications/<str:app>/', views.filterByApplicationView, name= 'AppView'),
    path('/snippetDetail/<int:pk>/', views.detailSnippetView.as_view(), name= 'Detail'),

]

snippets/models.py
from django.db import models

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.text import slugify
from ckeditor.fields import RichTextField


class Package(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ['name']

    def save(self, *args, **kwargs):
        val = getattr(self, 'name', False)
        if val:
            setattr(self, 'name', val)
        super(Package, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('snippets:snippetsAddSnippet')

class Language(models.Model):
    name = models.CharField(max_length=100, unique=True)
    packages = models.ManyToManyField(Package, related_name='language')

    class Meta:
        ordering = ['name']

    def save(self, *args, **kwargs):
        val = getattr(self, 'name', False)
        if val:
            setattr(self, 'name', val)
        super(Language, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class Application(models.Model):
    name = models.CharField(max_length=250, unique=True)

    class Meta:
        ordering = ['name']

    def save(self, *args, **kwargs):
        val = getattr(self, 'name', False)
        if val:
            setattr(self, 'name', val)
        super(Application, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class CodeSnippet(models.Model):
    name = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    language = models.ForeignKey(Language, on_delete=models.CASCADE, null=True)
    package = models.ManyToManyField(Package, related_name='snippets')
    application = models.ForeignKey(Application, on_delete=models.CASCADE, null=True)
    summary = models.CharField(max_length=500)
    code = RichTextField(blank=True, null=True)
    date_created = models.DateField(auto_now_add=True)
    last_modified = models.DateField(auto_now=True)
    slug = models.SlugField(max_length=50, unique=True, blank=True)

    class Meta:
        ordering = ['last_modified']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('snippets:Home')

    def save(self, *args, **kwargs):
        self.slug = self.slug or slugify(self.name)
        super(CodeSnippet, self).save(*args, **kwargs)

snippets/forms.py
from django import forms
from django.db.utils import OperationalError
from snippets.models import CodeSnippet, Package, Language, Application


class snippetsForm(forms.ModelForm):

    class Meta:

        model = CodeSnippet
        fields = ('name', 'author', 'language', 'package', 'application',
                  'summary', 'code')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control-small',}),
            'author': forms.TextInput(attrs={'value': '', 'id': 'writer', 'type': 'hidden'}),
            'language': forms.Select(choices=Language.objects.all().values_list('name', flat=True)),
            'package': forms.SelectMultiple(choices=Package.objects.all().values_list('name', flat=True)),
            'application': forms.Select(choices=Application.objects.all().values_list('name', flat=True)),
            'summary': forms.Textarea(attrs={'class': 'form-control',}),
            'code': forms.Textarea(attrs={'class': 'form-control',}),
        }

class snippetsEditForm(forms.ModelForm):

    class Meta:

        model = CodeSnippet
        fields = ('name', 'language', 'package', 'application',
                  'summary', 'code')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control-small', }),
            'language': forms.Select(choices=Language.objects.all().values_list('name', flat=True)),
            'package': forms.SelectMultiple(choices=Package.objects.all().values_list('name', flat=True)),
            'application': forms.Select(choices=Application.objects.all().values_list('name', flat=True)),
            'summary': forms.Textarea(attrs={'class': 'form-control', }),
            'code': forms.Textarea(attrs={'class': 'form-control', }),
        }
#
class snippetsAddLanguageForm(forms.ModelForm):

    class Meta:

        model = Language
        fields = ('name', )

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control-small',
                                           }),
        }

class snippetsAddPackageForm(forms.ModelForm):

    class Meta:
        model = Package
        fields = ('name',)

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control-small',
                                           }),
        }

class snippetsAddApplicationForm(forms.ModelForm):

    class Meta:
        model = Application
        fields = ('name',)

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control-small',
                                           }),
        }

snippets/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormMixin
from django.core import serializers
from django.contrib.auth import decorators, mixins
from snippets.models import CodeSnippet, Language, Package, Application
from snippets import forms as fms


DEBUG = True

# Create your views here.
def homeView(request):

    recent_snippets = CodeSnippet.objects.order_by('last_modified')[:10:-1]

    context = {'recent_snippets': recent_snippets}

    return render(request, 'snippetsHome.html', context)

def filterByLanguageView(request, lang):
    snippets = CodeSnippet.objects.filter(language__name__contains=lang)


    context = {'recent_snippets': snippets}

    return render(request, 'snippetsFiltered.html', context)

def filterByPackageView(request, pack):
    snippets = CodeSnippet.objects.filter(package__name=pack)


    context = {'recent_snippets': snippets}

    return render(request, 'snippetsFiltered.html', context)

def filterByApplicationView(request, app):
    snippets = CodeSnippet.objects.filter(application__name=app)

    context = {'recent_snippets': snippets}

    return render(request, 'snippetsFiltered.html', context)

def getLanguages(request):
    """Get unique languages in Model Language and return JSON """

    lang_json = serializers.serialize('json', Language.objects.all())
    print(f'\nLANGS: {lang_json}')
    return JsonResponse(lang_json, safe=False, content_type='application/json')

def getPackages(request):
    """Get unique packages in Model Package and return JSON """

    pack_json = serializers.serialize('json', Package.objects.all())
    print(f'\nPACKS: {pack_json}')
    return JsonResponse(pack_json, safe=False, content_type='application/json')

def getApplications(request):
    """Get unique packages in Model Package and return JSON """

    app_json = serializers.serialize('json', Application.objects.all())
    print(f'\nPACKS: {app_json}')
    return JsonResponse(app_json, safe=False, content_type='application/json')

def addSnippetView(request):
    form = fms.snippetsEditForm()

    if request.method == 'POST':
        form = fms.snippetsForm(request.POST)
        print(f'\nFORM: {form.errors}')
        if form.is_valid():
            form.save()

        return HttpResponseRedirect(reverse('snippets:Home'))

    context = {'form': form}

    return render(request, 'snippetAddSnippet.html', context)

class detailSnippetView(DetailView):
    model = CodeSnippet
    template_name = 'snippetsDetail.html'


class editSnippetView(mixins.UserPassesTestMixin, UpdateView):
    model = CodeSnippet
    form_class = fms.snippetsEditForm
    template_name = 'snippetsEditSnippet.html'

    def test_func(self):
        try:
            test = self.request.user.username == 'wodin'
        except AttributeError:
            test = False

        return test

class deleteSnippetView(mixins.UserPassesTestMixin, DeleteView):
    model = CodeSnippet
    template_name = 'snippetsDeleteSnippet.html'
    success_url = reverse_lazy('snippets:Home')

    def test_func(self):
        try:
            test = self.request.user.username == 'wodin'
        except AttributeError:
            test = False

        return test

def addPackageView(request):
    form = fms.snippetsAddPackageForm()

    if request.method == 'POST':
        form = fms.snippetsAddPackageForm(request.POST)
        if form.is_valid():

            form.save()
        return HttpResponseRedirect(reverse('snippets:AddSnip'))

    context = {'form': form, 'model': 'Package'}

    return render(request, 'snippetsAddEntry.html', context)

def addLanguageView(request):
    form = fms.snippetsAddLanguageForm()

    if request.method == 'POST':
        form = fms.snippetsAddLanguageForm(request.POST)
        if form.is_valid():

            form.save()
        return HttpResponseRedirect(reverse('snippets:AddSnip'))

    context = {'form': form, 'model': 'Language'}

    return render(request, 'snippetsAddEntry.html', context)

def addApplicationView(request):
    form = fms.snippetsAddApplicationForm()

    if request.method == 'POST':
        form = fms.snippetsAddApplicationForm(request.POST)
        if form.is_valid():

            form.save()
        return HttpResponseRedirect(reverse('snippets:AddSnip'))

    context = {'form': form, 'model': 'Application'}

    return render(request, 'snippetsAddEntry.html', context)

snippets/templates/snippetAddSnippet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% load static %}
    <link href="{% static 'css/snippetsStyle.css' %}" rel="stylesheet" media="screen">

    <div class="wrapper">
        <div class="card">
            {% if user.is_authenticated %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.media }}
                        <p> <h3>Snippet Name:</h3> {{ form.name }} </p>
                        <p><h3>Language: <span> (<a href="{% url 'snippets:AddLang' %}"> add </a></span>)</h3>
                            {{ form.language }} </p>
                        <p><h3>Package: <span> (<a href="{% url 'snippets:AddPack' %}">add</a>)</span></h3>
                            {{ form.package }} </p>
                        <p><h3>Application: <span> (<a href="{% url 'snippets:AddApp' %}">add</a>)</span></h3>>
                            {{ form.application }} </p>
                        <p> {{ form.code}} </p>
                        <p><h3>Summary:</h3>
                            {{ form.summary }} </p>

                        <br>
                        <button>Create</button>
                    </form>
            {% else %}
                <h3>You Shouldn't Be Here, go <a href="{% url 'snippets:Home' %}">home</a></h3>
            {% endif %}
        </div>
    </div>
</body>
</html>

snippets/templates/snippetsAddEntry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% load static %}
    <link href="{% static 'css/snippetsStyle.css' %}" rel="stylesheet" media="screen">

    <div class="wrapper">
        <div class="card">
            {% if user.is_authenticated %}
                    <form method="post" >
                        {% csrf_token %}
                        <p> <h3>New {{ model }}:</h3> {{ form.name }} </p>

                        <br>
                        <button>Add</button>
                    </form>
            {% else %}
                <h3>You Shouldn't Be Here, go <a href="{% url 'snippets:Home' %}">home</a></h3>
            {% endif %}
        </div>
    </div>
</body>
</html>

snippets/templates/snippetsDeleteSnippet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <h3 class="title"> Delete {{ CodeSnippet.name}} ?</h3>
    <div class="wrapper">
        <div class="card">
            {% if user.is_authenticated %}

                    <form method="post">
                        {% csrf_token %}
                        <button>Delete</button>
                    </form>

            {% else %}
                <h3>You Shouldn't Be Here, go <a href="{% url 'snippets:Home' %}">home</a></h3>
            {% endif %}
        </div>
    </div>

</body>
</html>

snippets/templates/snippetsDetail.html
<!DOCTYPE html>
<html lang="en">

{% extends 'snippetsHome.html' %}
<body>
{% block sidenav %}

{% endblock %}

{% block snippets-main %}


{% endblock %}

</body>
</html>

snippets/templates/snippetsEditSnippet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% load static %}
    <link href="{% static 'css/snippetsStyle.css' %}" rel="stylesheet" media="screen">

    <div class="wrapper">
        <div class="card">
            {% if user.is_authenticated %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.media }}
                        <p> <h3>Snippet Name:</h3> {{ form.name }} </p>
                        <p><h3>Language: <span> (<a href="{% url 'snippets:AddLang' %}"> add </a></span>)</h3>
                            {{ form.language }} </p>
                        <p><h3>Package: <span> (<a href="{% url 'snippets:AddPack' %}">add</a>)</span></h3>
                            {{ form.package }} </p>
                        <p><h3>Application: <span> (<a href="{% url 'snippets:AddApp' %}">add</a>)</span></h3>>
                            {{ form.application }} </p>
                        <p> {{ form.code}} </p>
                        <p><h3>Summary:</h3>
                            {{ form.summary }} </p>

                        <br>
                        <button>Update</button>
                    </form>
            {% else %}
                <h3>You Shouldn't Be Here, go <a href="{% url 'public:home' %}">home</a></h3>
            {% endif %}
        </div>
    </div>
</body>
</html>

snippets/templates/snippetsFiltered.html
<!DOCTYPE html>
<html lang="en">

{% extends 'snippetsHome.html' %}

snippets/templates/snippetsHome.html
<!DOCTYPE html>
<html lang="en">
{% block title %}
    <head>
        <meta charset="UTF-8">

        <title>Snippets Home</title>

    </head>
{% endblock %}
<body>
    {% block sidenav %}
    <nav>
        <button class="openbtn" onclick="openNav()">Menu</button>
    </nav>
        {%  load static %}
        <link href="{% static 'css/snippetsStyle.css'%}" rel="stylesheet" media="screen">
        <script src="{% static 'js/snippets.js' %}"></script>

        <div id="mySidenav" class="sidenav" >
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <div class="dropdown">
                    <a class="dropbtn" onclick="updateMenu({% url "snippets:GetLangs" %}, 'languages')" >Language</a>
                    <div class="dropdown-content" id="languages">
                    </div>
            </div>
            <div class="dropdown">
                    <a class="dropbtn" onclick="updateMenu({% url "snippets:GetPacks" %}, 'packages')">Package</a>
                    <div class="dropdown-content" id="packages" ></div>
            </div>
            <div class="dropdown">
                <a class="dropbtn" onclick="updateMenu({% url 'snippets:GetApps' %}, 'applications')">Application</a>
                    <div class="dropdown-content" id="applications"></div>
            </div>
            <div class="homeBtn" id="homeBtn">
                <a class="homeBtn" href="{% url 'snippets:Home' %}">Snippets Home </a>
            </div>
            <div class="addSnip">
                <a class="addSnip" href="{% url 'snippets:AddSnip' %}">Add Snippet </a>
            </div>
        </div>
    {% endblock %}
    {% block snippets-main %}
    <div id="main">

        <div class="card">
            {% for snippet in recent_snippets %}
                <div>
                    <h3><a href="{% url 'snippets:Detail' snippet.pk %}">{{ snippet.name }}</a></h3>
                    <P> {{ snippet.summary}} </P>
                    <div class="snippet-info-block">
                        <small>
                            Created: {{ snippet.date_created }}
                            <a href="{% url 'snippets:EditSnip' snippet.pk %}  ">   edit</a>
                            <a href="{% url 'snippets:DelSnip' snippet.pk %}  ">   delete</a>
                            <br>
                            {% for package in snippet.package.all %}
                                |<a class="small-a" href="#">{{ package }}</a>
                            {% endfor %}
                                |
                                <br>
                        </small>
                    </div>
                    <p class="snippet-code"> {{ snippet.code | safe }} </p>
                </div>
            {% endfor %}
        </div>
    </div>
    {% endblock %}


</body>

</html>